version: '3'

services:
  rp:
    build: ./rp
    ports:
      - "4444:4444"
    environment:
      - IDP_HOST=idp
      - REDIRECT_URI=http://localhost:4444/callback
      - MODE=dev
    depends_on:
      - idp
      - mongo-rp
  idp:
    build: ./idp
    ports:
      - "4445:4445"
    environment:
      - REDIRECT_URI=http://localhost:4444/callback
  mongo-rp:
    image: mongo
    volumes:
      - mongo-data-rp:/data/db
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js

volumes:
  mongo-data-rp:
    driver: local